"""Run the single active v2.1.0 reproducibility and integration route.

The default mode is the strict fresh-archive gate. ``--rerun`` repeats the
same retained scientific route in an already-used tree while retaining
runtime and immutable-source verification.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from functions.figure_io import remove_orphaned_figure_staging_files
from functions.integrity import (
    ARCHIVE_MANIFEST_PATH,
    IMMUTABLE_MANIFEST_PATH,
    PREFLIGHT_ENVIRONMENT_VARIABLE,
    archive_preflight_token,
    verify_manifest,
)
from functions.io_utils import remove_orphaned_output_staging_files
from functions.runtime_contract import verify_runtime_versions


ACTIVE_STEPS = (
    ("diagnostics", "scripts/01_run_diagnostics.py"),
    ("tables", "scripts/02_make_tables.py"),
    ("figures and curve data", "scripts/03_generate_figures.py"),
    ("sensitivity and robustness", "scripts/04_run_sensitivity_checks.py"),
    ("operational primitive checks", "scripts/10_run_operational_primitive_checks.py"),
    ("operational innovation checks", "scripts/11_run_operational_innovation_checks.py"),
    ("operational solver-entry checks", "scripts/12_run_operational_solver_entry_checks.py"),
    ("operational rolling-path checks", "scripts/13_run_operational_path_checks.py"),
    ("operational robustness checks", "scripts/14_run_operational_robustness_checks.py"),
    ("clock and subordination entry checks", "scripts/16_run_clock_subordination_checks.py"),
    ("clock-only theory/estimator conformity", "scripts/26_run_clock_only_conformity.py"),
    ("corrected translation-mode coupling recovery", "scripts/29_run_corrected_coupling_recovery.py"),
    ("combined clock and corrected-coupling no-refit prediction", "scripts/30_run_combined_no_refit_prediction.py"),
    ("Stage 8 event semantics and impact entry", "scripts/32_run_event_semantics_entry.py"),
    ("paired single-trade own and cross impact", "scripts/33_run_single_trade_impact.py"),
    ("scheduled meta-order own and cross impact", "scripts/34_run_meta_order_impact.py"),
    ("mid-price and trade-sign dependence", "scripts/35_run_dependence_diagnostics.py"),
    ("final estimator-aware combined Epps integration", "scripts/36_generate_final_epps_integration.py"),
    ("fixed-time order-book shock recovery", "scripts/40_run_order_book_shock_recovery.py"),
    ("current-model stylised-facts recovery", "scripts/41_run_stylised_facts_recovery.py"),
    ("R13 long-memory clocks and paired impact", "scripts/43_run_r13_long_memory_clock_impact.py"),
    ("v2.1.0 integration verification", "scripts/42_run_v2_1_integration_verification.py"),
)


def _run(label: str, command: list[str], environment: dict[str, str]) -> None:
    print(f"\n[{label}] {' '.join(command)}", flush=True)
    subprocess.run(command, cwd=PROJECT_ROOT, env=environment, check=True)


def _parse_args(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rerun",
        action="store_true",
        help=(
            "repeat the route in an already-used tree; verify immutable sources "
            "and scientific outputs instead of requiring fresh generated bytes"
        ),
    )
    return parser.parse_args(arguments)


def main(arguments: list[str] | None = None) -> int:
    options = _parse_args(arguments)
    remove_orphaned_output_staging_files()
    try:
        versions = verify_runtime_versions()
        if options.rerun:
            integrity_entries = verify_manifest(IMMUTABLE_MANIFEST_PATH)
        else:
            integrity_entries = verify_manifest(ARCHIVE_MANIFEST_PATH)
    except RuntimeError as error:
        print(f"Preflight failed: {error}")
        return 1
    print(
        "Runtime contract verified: "
        + ", ".join(f"{package} {version}" for package, version in versions.items())
        + "."
    )
    if options.rerun:
        print(
            "Rerun preflight verified: "
            f"{integrity_entries} immutable entries, 0 failures."
        )
        print(
            "Generated artifacts will be checked numerically and scientifically; "
            "fresh-archive byte identity is not asserted in rerun mode."
        )
    else:
        print(
            "Fresh-archive manifest verified: "
            f"{integrity_entries} entries, 0 failures."
        )
    environment = os.environ.copy()
    environment[PREFLIGHT_ENVIRONMENT_VARIABLE] = archive_preflight_token()
    environment.setdefault(
        "MPLCONFIGDIR",
        str(Path(tempfile.gettempdir()) / "correlation-emergence-matplotlib"),
    )
    python = sys.executable
    steps = tuple((label, [python, path]) for label, path in ACTIVE_STEPS) + (
        ("regression tests", [python, "-m", "unittest", "discover", "-s", "tests", "-v"]),
        ("immutable-source integrity", [python, "scripts/00_verify_immutable_manifest.py"]),
    )
    try:
        for label, command in steps:
            if label == "regression tests":
                remove_orphaned_figure_staging_files()
                remove_orphaned_output_staging_files()
            _run(label, command, environment)
    except subprocess.CalledProcessError as error:
        print(f"\nActive route stopped after an unsuccessful command (exit code {error.returncode}).")
        return error.returncode or 1
    print("\nActive v2.1.0 reproducibility route completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
